### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by mateusz-nalepa** [ldaume/headless-chrome#1]
First of all, thanks for your great dependency!
I ran some example on Linux OS.
Is it possible to run dependency on Windows OS?
As I know, Chrome 59 beta is released on Windows.

**Comment by ldaume** [comment]
Hi @starwarsjk ,

thanks for your comment. I'll check that until Saturday.

Have a nice day,
Lenny

**Comment by ldaume** [comment]
The main problem is that the latest [Chromedriver](https://sites.google.com/a/chromium.org/chromedriver/downloads) 2.29 supports Chrome up to version 58 but the headless mode is available in version 59+ and there is currently no windows version of the dev sources.

**Comment by mateusz-nalepa** [comment]
Thanks for checking. I am waiting now for support from [https://sites.google.com/a/chromium.org/chromedriver/downloads](url)

**Comment by mateusz-nalepa** [comment]
Hi @ldaume 
there is already a new version of ChromeDriver with support for Chrome v58-60! 
Can you try to run dependency on Windows OS?

Thank you in advance!
