### ISSUE TITLE
0.1.4 jar missing in Maven Repo

### ISSUE THREAD

**Issue by tomcashman** [ldaume/headless-chrome#2]
Hi,

I wanted to download the latest release version but it looks like the 0.1.4 jar is missing in the repository -> https://maven.reinvent-software.de/nexus/content/groups/public/software/reinvent/headless-chrome/0.1.4/

Compared to the 0.1.3 release -> https://maven.reinvent-software.de/nexus/content/groups/public/software/reinvent/headless-chrome/0.1.3/

**Comment by ldaume** [comment]
@tomcashman , thanks for your issue. I hope it is fixed, now.

Happy coding,
Lenny
