### ISSUE TITLE
Headless Chrome is capturing only white screenshot for intranet sites.

### ISSUE THREAD

**Issue by snpanigrahi9** [ldaume/headless-chrome#7]
Chrome version : 60.0.3112.101
Platform        :  Windows 7
ChromeDriver  : 2.32
Selenium-java  : 3.5.3

Sample testcase below

same code is working when i am capturing screenshot for http://www.google.com
But it is not working for intranet sites for
https://newcointranet.com/
https://pfo-18422.dev.upoint.hewitt.com/web/hmorg/client-tooling-login

package demo1;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver; 
import org.openqa.selenium.chrome.ChromeDriver; 
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait; 

public class Headless {

	public static void main(String[] args) throws InterruptedException, IOException
	{ 
		
		System.setProperty("webdriver.chrome.driver", "C:\\MyWorkspace\\Demo\\chromedriver.exe");
		ChromeOptions chromeOptions = new ChromeOptions();
		chromeOptions.addArguments("--headless");
		chromeOptions.addArguments("window-size=1280,1696");
		WebDriver driver = new ChromeDriver(chromeOptions);
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		driver.get("https://newcointranet.com/");
		Thread.sleep(10000);
		System.out.println(driver.getTitle());
		
	File screenshotFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
	FileUtils.copyFile(screenshotFile, new File("C:\\Users\\A0705286\\Desktop\\ScreenShot\\first.bmp"));

Starting ChromeDriver 2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a) on port 16433
Only local connections are allowed.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Sep 19, 2017 4:51:29 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

**Comment by FibreFoX** [comment]
Have you tried to set the window-size via `driver.manage().window().setSize(new Dimension(1280,1696));` instead of usind `chromeOptions.addArguments("window-size=1280,1696");` ?

**Comment by snpanigrahi9** [comment]
Thanks...its working now.
But its not working for https internal sites.
I am going raise new bug.
